services:
  ollama_deepseek_r1_local:
    build:
      dockerfile: Dockerfile_Ollama
    container_name: ollama_deepseek_r1_local
    environment:
      - OLLAMA_KEEP_ALIVE=5m # デフォルトは5m、5分後にモデルがアンロード、-1で無制限
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434" # ollama用
    working_dir: /work
    volumes:
      - ../work:/work
      - ollama:/root/.ollama # ollama用

  open-webui:
    build:
      dockerfile: Dockerfile_OpenWebUI
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=False
    volumes:
      - ../open-webui:/app/backend/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama: